### ISSUE TITLE
Change DesignDoc ID in runtime

### ISSUE THREAD

**Issue by MarcFerrerVWGS** [google/automotive-design-compose#1144]
Hello,

Currently we have two figma documents with id's "abc" and "xyz" and we want to load depending on the configuration we need.
The only thing we want to change is the ID because the designcomponents are the same.

Here's the example:
```
@DesignDoc(id = "abc")
interface StageFrame {
    @DesignComponent(node = "#stage", isRoot = true)
    fun Stage()
}

class MainActivity : ComponentActivity() {

override fun onCreate(savedInstanceState: Bundle?) {

        super.onCreate(savedInstanceState)
        val displayMetrics = DisplayMetrics()
        windowManager.defaultDisplay.getMetrics(displayMetrics)
        val height = displayMetrics.heightPixels
        val width = displayMetrics.widthPixels
        if(height == 1260 && width == 2240) {
            // Change documentID to abc
        }
        else {
            // Change documentID to xyz
        }
        setContent {
            Stage()
        }
}
``` 
In this example we want to change the id and loading the same Stage elements but from a different id document. There's somehow to implement that?

**Comment by rylin8** [comment]
You can use the `DesignDocOverride` function like this:

```
DesignDocOverride("MCHaMYcIEnRpbvU9Ms7a0o") {
    Stage()
}
```

In 0.27, you'll need to wrap the ID around `DesignDocId` like this:

```
DesignDocOverride(DesignDocId("MCHaMYcIEnRpbvU9Ms7a0o")) {
    Stage()
}
```

**Comment by rylin8** [comment]
Closing, please re-open if this is still an issue.
