### ISSUE TITLE
Update dials and gauges plugin UI

### ISSUE THREAD

**Issue by rylin8** [google/automotive-design-compose#116]
Per Aubrey's design
![Screenshot 2023-06-07 at 4 35 00 PM](https://github.com/google/automotive-design-compose/assets/130500397/df7ff487-03d6-4e00-b718-27ac4ddea04f)

**Comment by iamralpht** [comment]
Triage discussion: @aubreydagoog is working on some more updates, will share with @miriamvu and the rest of the team later today.
