### ISSUE TITLE
Add squoosh support for component replacement with a non-DesignCompose composable

### ISSUE THREAD

**Issue by rylin8** [google/automotive-design-compose#1214]
Doing a component replacement in squoosh where the composable does not call into DesignCompose (such as a Box()), renders nothing.

**Comment by iamralpht** [comment]
I thought that the video example worked OK, and we're showing maps in DriverUI (via `AndroidView` wrapping a `SurfaceView` or something similar). Does one of the tests fail on this case? (If so, I can have a go at fixing it).

**Comment by rylin8** [comment]
This is done
