### ISSUE TITLE
DesignComposables don't reset state between tests in a single test process

### ISSUE THREAD

**Issue by timothyfroehlich** [google/automotive-design-compose#1218]
Example code:

```
@Test
fun canExpandDesignSwitcher() {
    with(composeTestRule) {
        setContent { DesignSwitcherTest(testName = testName) } // Add the Design Switcher
        captureRootRoboImage("CollapsedSwitcher") // Capture a screenshot. It will show the collapsed Design Switcher
        onDCDoc(DesignSwitcherDoc).performClick() // Click it to expand it
        captureRootRoboImage("ExpandedSwitcher") // Capture a screenshot of the expanded switcher

    }
}
@Test
fun designSwitcherHasReset() {
    with(composeTestRule) {
        setContent { DesignSwitcherTest(testName = testName) } // Add the Design Switcher
        captureRootRoboImage("NewTestRun") // Capture a screenshot of the Design Switcher

    }
}
```

These tests are run within the same test class and will produce three screenshots. "CollapsedSwitcher" will display the Design Switcher in it's default state:
![image](https://github.com/google/automotive-design-compose/assets/5819722/9e7ed699-ecd0-4c51-acdc-8b73021d2d1d)

Then the DesignSwitcher is clicked and "ExpandedSwitcher" will show it's expanded state:

![image](https://github.com/google/automotive-design-compose/assets/5819722/691639be-125f-427b-ae02-5f7462ed5ebf)

The test ends and `designSwitcherHasReset` starts and captures an image of the initial state of the DesignSwitcher within the test.

**Expected Result**
The image will show the collapsed switcher.

**Actual Result**
The image will show the expanded switcher.

**Cause**

The [InteractionStateManager](https://github.com/google/automotive-design-compose/blob/9ce214f3d56a7e6d810f4b00b7ec72c50f66c5db/designcompose/src/main/java/com/android/designcompose/InteractionState.kt#L769), which stores the state of each DesignComposable's possible interactions, is global and as such does not reset between test runs.

**Workaround**

Running `InteractionStateManager.states.clear()` before each test (such as within an `@Before` function) will manually clear it and reset the state. This is probably only available for tests that run within the DesignCompose core library tests, however, because the InteractionStateManager is `internal`.

**Comment by yiqunw700** [comment]
It also happens for RenderAllExamples test and Interaction Trigger test which load the same design file during github workflow checks.  Clearing the interaction states fix that.

Not sure why it doesn't happen on local machine.
