### ISSUE TITLE
How generate local release AAR

### ISSUE THREAD

**Issue by spkdroid** [google/automotive-design-compose#1254]
Hi,

I'm making modification to the design compose folder and need to make special AAR for a particular Use Case.

Does anyone know how to perform the local release AAR file.

Thanks

**Comment by timothyfroehlich** [comment]
Hi! I'm kind of curious what you're up to :) But either way, you can build a full set of release AARs by running `./gradlew publishReleasePublicationToLocalDirRepository`. You can configure where they'll build with the `DesignComposeMavenRepo` Gradle property, but without that property it'll just build it to the `designcompose/build/designcompose_m2repo` directory.

**Comment by spkdroid** [comment]
@timothyfroehlich thank you so much.

For few figma designs we had to make scalling or apply modifiers. I'm planning to make the change inside the library and have it build it as a special AAR file.

**Comment by timothyfroehlich** [comment]
We'd be super interested in the changes you've made if you'd be willing to share.

**Comment by spkdroid** [comment]
@timothyfroehlich  sure, let me finish the change and try to provide the feedback back to you.
