### ISSUE TITLE
Migrate the Variables to crates/dc_bundle

### ISSUE THREAD

**Issue by timothyfroehlich** [google/automotive-design-compose#1292]
This will take a bit more than just moving the declarations and fixing imports. Most of the variable types's functions use structs from `figma_schema.rs`. I'm unsure how much of the variable code from `figma_schema.rs` should be moved to `dc_bundle`. @rylin8 I think I'll need your help here.

**Comment by rylin8** [comment]
@timothyfroehlich pretty sure this should be closed. Reopen if not.
