### ISSUE TITLE
Break out dependabot updates in generated release notes

### ISSUE THREAD

**Issue by iamralpht** [google/automotive-design-compose#1318]
The machine generated release notes are hard to read because they're dominated by dependabot updates, which aren't super interesting to most consumers of the library. For now (at least), the human authored changes are more relevant ;)

**Comment by timothyfroehlich** [comment]
So I've had an idea about this. GitHub has an action that lets you combine PRs into a single one, which is intended to be used for Dependabot, but it requires a personal access token or GitHub App, which would require approval from the Google org.

But Dependabot's configuration does let you set a `target-branch`. So what we can do is to create a side branch (named "dependapool") and merge the PRs into it. Then once we've finished a whole batch of them we can squash-merge from the side branch back into main and reset the side-branch back to main. This would mean that we only have one Dependabot commit to main per week.

What do you think?

**Comment by iamralpht** [comment]
Yeah, this sounds really good. I'd like to start doing more detailed release notes again, but I thought, even without that we could make the machine generated release notes more readable.

**Comment by timothyfroehlich** [comment]
TAL at the linked PR's then :)
