### ISSUE TITLE
Cannot get the tutorial working ("Invalid Token", "Network error")

### ISSUE THREAD

**Issue by StephanSchuster** [google/automotive-design-compose#1335]
I wanted to try out ADC and followed each step very closely. I restarted from scratch 5 times, created 3 different Figma tokens, tested multiple commit states of ADC, used mobile and automotive emulators each in API 33 and 34 as well as Pixel Tablet device, with VPN and without, ...

The result is always the same:
```
I  Starting Live Updates
I  Figma token set
D  Overlay start
I  dc_jni::layout_manager: jni_add_nodes: 34 nodes, layout_id 7
I  dc_jni::layout_manager: jni_add_nodes: 34 nodes, layout_id 7
D  Compat change id reported: 289878283; UID 10194; state: ENABLED
D  HandleResponse 4, changed: [18, 25, 36, 8, 27, 26, 9, 10, 32, 24, 37, 23, 11, 7, 39, 35, 40, 20, 30, 21, 14, 13, 33, 22, 38, 19, 17, 29, 12, 15, 34, 31, 16, 28]
D  Overlay end
I  HTTP Proxy: not set
I  dc_jni::layout_manager: jni_add_nodes: 1 nodes, layout_id 1
I  dc_jni::layout_manager: jni_add_nodes: 1 nodes, layout_id 1
D  HandleResponse 5, changed: [3, 1, 4, 2]
I  dc_jni::layout_manager: jni_add_nodes: 1 nodes, layout_id 1
I  dc_jni::layout_manager: jni_add_nodes: 1 nodes, layout_id 1
D  HandleResponse 6, changed: [2, 1, 3, 4]
E  dc_jni::error_map: Network Error: Figma_import Error, HTTP Error
E  Live update for KMH5pJX failed: Invalid Token
```

**Any idea what I am doing wrong?** I am 1000% sure it is the right Figma token I use. When running with debug I can also see the expected token being used in `DocServer.kt`.

BTW: On an AAOS API 34 Emulator the DesignSwitcher looks okayish to me while on a mobile API 34 emulator and on a real Pixel Tablet device it looks completely broken.

![Screenshot_1720535070](https://github.com/google/automotive-design-compose/assets/5207269/a6df0a3e-9104-44a6-9464-33d20677fbba)
![Screenshot_1720534961](https://github.com/google/automotive-design-compose/assets/5207269/3152ebcd-d8c5-497d-a8af-2b76da4b81f4)

**Comment by iamralpht** [comment]
I think this is likely because your Figma API key doesn't have access to variables -- we recently added support for Design Tokens via Variables, and the error message if your token doesn't have variable access is confusing. We'll clean this up in #1296 -- please give that a try and see if it addresses the Invalid Token issue.

Let's keep this ticket open for the layout issue you saw on the mobile emulator...

**Comment by StephanSchuster** [comment]
Thanks @iamralpht for your response. Not sure if I understood everything correctly.

This is what I see when creating new access tokens in Figma.
![image](https://github.com/google/automotive-design-compose/assets/5207269/4f8d6c30-65b6-4bad-9f5b-9b20df0f2e34)

There is nothing related to "variables". Is this why the other issues says "I don't think we should restrict access to enterprise users." and I am no enterprise user? Not sure. I thought I am. I am a developer. Need to check about that variable thing with my designers.

Nevertheless, I yesterday also created a token with everything set to full access - as far as possible for me. This did not make any difference.

**Comment by StephanSchuster** [comment]
But here is another finding which might help you to find the root cause.

- Do a fresh clone of `https://github.com/google/automotive-design-compose.git`
- Launch Android Studio (Jellyfish for me) on `reference-apps/tutorial`

Default in terms of [dependencies](https://github.com/google/automotive-design-compose/blob/main/reference-apps/tutorial/app/build.gradle.kts#L76) is:
```
implementation(libs.designcompose)
ksp(libs.designcompose.codegen)
```
which [points](https://github.com/google/automotive-design-compose/blob/main/gradle/libs.versions.toml#L3) to `designcompose = "0.29.0-SNAPSHOT"`

After hardcoding this to 27.0.0 everything seems to work again. At least I can see the Figma Doc etc. in my app and do simple changes. Still need to do the tutorial to see if everything works.
```
implementation("com.android.designcompose:designcompose:0.27.0")
ksp("com.android.designcompose:codegen:0.27.0")
```

`0.28.0` does not work ("Invalid token" as described before)
`0.29.0-SNAPSHOT` does not work ("Could not resolve all files ..." on build)

**Comment by timothyfroehlich** [comment]
> Thanks @iamralpht for your response. Not sure if I understood everything correctly.
> 
> This is what I see when creating new access tokens in Figma. ![image](https://private-user-images.githubusercontent.com/5207269/347477459-4f8d6c30-65b6-4bad-9f5b-9b20df0f2e34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NDExMjksIm5iZiI6MTcyMDY0MDgyOSwicGF0aCI6Ii81MjA3MjY5LzM0NzQ3NzQ1OS00ZjhkNmMzMC02NWI2LTRiYWQtOWY1Yi05YjIwZGYwZjJlMzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTBUMTk0NzA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTYyZmYwYzRjZTc4ODFjMTZhNzQxNzVlMjJjODJmMGI0N2I2MTc3MGY1MmY3OTY0ZTA4MzljYWE0YTZkOTRhZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PLeHtoG0WlbgP5A8mEK0FxhmJxOrnjx2t1-Yx8xosiU)
> 
> There is nothing related to "variables". Is this why the other issues says "I don't think we should restrict access to enterprise users." and I am no enterprise user? Not sure. I thought I am. I am a developer. Need to check about that variable thing with my designers.
> 
> Nevertheless, I yesterday also created a token with everything set to full access - as far as possible for me. This did not make any difference.

@iamralpht He may have a lower tier account that doesn't have access to variables. Like [Rob said](https://github.com/google/automotive-design-compose/issues/1296#issuecomment-2203845185), we need to make some fixes here.

@StephanSchuster It looks like you'll need to stick with 0.27 for now.

**Comment by StephanSchuster** [comment]
@timothyfroehlich, @iamralpht
I talked to my UX team. I have a "full design seat" and "full dev mode seat". Next step would be "admin".

And in Figma I can see/use variables:
![image](https://github.com/google/automotive-design-compose/assets/5207269/a50f6731-7984-4998-80f3-d34d989cec1a)

**Comment by timothyfroehlich** [comment]
It's not that, it's access to the REST API for Variables. It requires your whole team to be on the "Enterprise" plan. 

<img width="1542" alt="image" src="https://github.com/google/automotive-design-compose/assets/5819722/c9dcb6b3-d568-450a-b2b0-53b2478f5077">

I'm still waiting on @iamralpht to help us decide what's best to do here.

**Comment by timothyfroehlich** [comment]
@StephanSchuster I've created #1351 to better track this.

**Comment by StephanSchuster** [comment]
Ah, now it makes sense. Understood. We are apparently on an "Organization" plan.
Thanks for explaining and opening a dedicated issue with high priority, @timothyfroehlich.

Feel free to close or keep this issue. With 27 the UI/layout issue mentioned in a plain mobile emulator or Google Pixel device is also somehow solved. I mean the DesignSwitcher looks broken in the beginning, but once the file is loaded it looks as intended.

**Comment by rylin8** [comment]
Closing as I believe this has been resolved.
