### ISSUE TITLE
Invalid @Design parameter type State<String>

### ISSUE THREAD

**Issue by StephanSchuster** [google/automotive-design-compose#1366]
Hopefully I did not miss something, but the code as described in
https://google.github.io/automotive-design-compose/docs/modifiers/modifiers#text-content-with-state

results in `e: [ksp] Invalid @Design parameter type State<String>`

I did not debug, but maybe this mapping did not work?
https://github.com/google/automotive-design-compose/blob/4dd69e283fcff3a0855c0bfdec2db951c972923c/codegen/src/main/kotlin/com/android/designcompose/codegen/Common.kt#L177

Here is my code (same as in docs):

```
import androidx.compose.runtime.State
...

@DesignDoc(id = "...")
interface Test {

    @DesignComponent(node = "#Frame1")
    fun Frame1(
        @Design(node = "#text") text: State<String>
    )

}
```

**Comment by yiqunw700** [comment]
Works on my end. Maybe try cleaning the project and rebuild?

Does the validation app build for you? It uses the State<String> in the [StateCustomizations.kt test](https://github.com/google/automotive-design-compose/blob/4dd69e283fcff3a0855c0bfdec2db951c972923c/integration-tests/validation/src/main/java/com/android/designcompose/testapp/validation/examples/StateCustomizations.kt#L38) too.

**Comment by StephanSchuster** [comment]
Strange. Not sure what I am doing wrong then. I tested with 0.27.0 and 0.28.0 in a minimal, new app - including clean, rebuild, invalidate, restart etc.

I cannot test the validation app since I am still unable to build ADC from source code. There is some issue with `cargo` and `ring`. But this is another topic and probably only on my machine.

If you ever find the time to test the `State<String>` example in a dedicated minimal app, please let me know.

**Comment by yiqunw700** [comment]
Sorry for the confusion. The code change to support State<String> is not in any release yet but the document change is visible to the public immediately.
Please try again when our next release is available.

**Comment by StephanSchuster** [comment]
Thanks @yiqunw700 , just noticed it myself when I checked git blame. I should have noticed it earlier. Sorry.
