### ISSUE TITLE
Arc meter customizations sometimes render incorrectly

### ISSUE THREAD

**Issue by rylin8** [google/automotive-design-compose#147]
Some arcs in Figma that are setup with the arc meter customization with our Dials and Gauges plugin is rendered incorrectly. This seems to happen with flipped axes, negative sweeps, or a combination of both.

![Screenshot 2023-06-27 at 2 43 59 PM](https://github.com/google/automotive-design-compose/assets/130500397/7eb17dba-a7db-4d99-8155-8f2e139e0b8f)

**Comment by timothyfroehlich** [comment]
Could you provide reproduction steps? Perhaps a small Figma file that shows the issue?

**Comment by rylin8** [comment]
I don't know how to reproduce this exactly, but it was happening in our Cluster design. I suspect it has to do with negative sweeps and flipped axes because that's what was happening in the Cluster, but this never happened in any of the arcs in the dial & gauges test doc. The reproduction steps are to enable and arc for meter customization and change the sweep parameters and flip the axes until this happens.

**Comment by rylin8** [comment]
I believe this only happens when the arc has a fill. When there is a fill and it has a meter customization, the code takes a different path where it manually draws the outline of the arc with a bunch of arcs and bezier curves.
