### ISSUE TITLE
Progress bars don't respond to layout changes

### ISSUE THREAD

**Issue by iamralpht** [google/automotive-design-compose#1493]
I made a design with some progress bars that get wider based on the layout (the parent fills its parent, the ultimate parent is resizable). The progress bar uses the width from the design doc (rather than the width from the parent layout) to determine its size -- so as the progress bar gets resized, the filled proportion doesn't change.

I observed this using squoosh, but I think the code path is the same for non-squoosh, too.

**Comment by rylin8** [comment]
I think this will be easier to fix in squoosh since nodes have a pointer to their parent, but in non-squoosh I don't think there's an easy way to get the parent's layout size.
