### ISSUE TITLE
Serialized files out of date

### ISSUE THREAD

**Issue by timothyfroehlich** [google/automotive-design-compose#161]
Manual tests not passing - dev-scripts/test-all.sh needs to pass.

**Comment by timothyfroehlich** [comment]
@srahman80 at one point you said you were going to work on this?

**Comment by srahman80** [comment]
Sorry was on the road yesterday.  Yes, I can work on that.  I think I was
waiting for an update to the readme regarding generation of the files (to
make sure I was generating the correct files)

**Comment by timothyfroehlich** [comment]
@srahman80 Sorry about that, you're right, I didn't get around to writing that. Here's a partial update to the readme with the information you need: https://github.com/google/automotive-design-compose/pull/165
