### ISSUE TITLE
Squoosh regression - DesignComponent cannot have tap callback on itself

### ISSUE THREAD

**Issue by HooHaa-code** [google/automotive-design-compose#1709]
With useSquoosh = false, the following tap callback snippet works as expected:

```@DesignComponent(node = "IconButton")
    fun iconButton(
        @DesignVariant(property = "state") state: State,
        @Design(node = "#iconContainer") icon: @Composable (ComponentReplacementContext) -> Unit,
        @Design(node = "IconButton") onPress: TapCallback,
    )
```

When squoosh is enabaled, the tap callback no longer works. 

I have attached an example project
[Ex4Google-tapCallback.zip](https://github.com/user-attachments/files/17262253/Ex4Google-tapCallback.zip)

**Comment by yiqunw700** [comment]
Hi @HooHaa-code, could you please provide the DesignCompose release version? Thanks!

https://github.com/google/automotive-design-compose/pull/1502 squoosh support for `TapCallbak` was added in 0.30.

**Comment by HooHaa-code** [comment]
I have "+" in libs.version.toml

As of today the latest version is v0.31.0-rc01
