### ISSUE TITLE
Squoosh image customization support

### ISSUE THREAD

**Issue by yiqunw700** [google/automotive-design-compose#1719]
Image customization or image with context customization is not supported by squoosh

**Comment by rylin8** [comment]
Is this done or are you working on image with context customization? I think we can make image with context a separate issue, and if you haven't done it yet I have some thoughts on it.

**Comment by yiqunw700** [comment]
> Is this done or are you working on image with context customization? I think we can make image with context a separate issue, and if you haven't done it yet I have some thoughts on it.

Not actively working on the `ImageWithContext` customization cause it uses a `@Composable` which seems hard to fit in the squoosh structure. I was trying to remove the `@Composable` annotation but not very sure about it. What're your thoughts?

I will make a different issue.
