### ISSUE TITLE
Setting Figma stroke for individual side will render in compose for all sides

### ISSUE THREAD

**Issue by Heneveld** [google/automotive-design-compose#176]
![render_compose](https://github.com/google/automotive-design-compose/assets/138029735/1cb3389a-a030-4909-9d49-248261cd5d0f)
![outline_bottom_figma](https://github.com/google/automotive-design-compose/assets/138029735/30b9c526-11ba-4079-87a8-4584f389337c)

**Comment by timothyfroehlich** [comment]
Hi! We took a look and we don't currently support setting strokes for individual sides. We'll be looking into what it will take to support this.

**Comment by iamralpht** [comment]
This is fixed in the upcoming 0.24 release -- resolving the ticket.
