### ISSUE TITLE
Cargo build tasks fail on windows

### ISSUE THREAD

**Issue by HooHaa-code** [google/automotive-design-compose#372]
This is possibly and issue with file extensions

designcompose:cargoBuildX86Debug
designcompose:cargoBuildArm64-v8aDebug
designcompose:cargoBuildArmeabi-v7aDebug
designcompose:cargoBuildX86_64Debug

All fail with the same error:

```
A problem was found with the configuration of task ':designcompose:cargoBuildX86Debug' (type 'CargoBuildTask').
  - Type 'com.android.designcompose.cargoplugin.CargoBuildTask' property 'cargoBin' specifies file '<HOME_DIR>\.cargo\bin\cargo' which doesn't exist.
```

The file does exist in that location.  Editing CargoPlugin.kt  line 114 to add an exe will allow the task to continue:

```
 task.cargoBin.set(
                    cargoExtension.cargoBin.orElse(
                        project.providers.systemProperty("user.home").map {
                            File(it, ".cargo/bin/cargo")
                        }
                    )
                )
```

change to:

```
task.cargoBin.set(
                    cargoExtension.cargoBin.orElse(
                        project.providers.systemProperty("user.home").map {
                            File(it, ".cargo/bin/cargo.exe")
                        }
                    )
                )

```

After making this change the four task still fail but with this error:
`could not exec the linker '<HOME_DIR>\AppData\Local\Android\Sdk\ndk\25.2.9519653\toolchains\llvm\prebuilt\windows-x86_64\bin\i686-linux-android26-clang'`

**Comment by timothyfroehlich** [comment]
Hi! I admit, I hadn't taken the time to make sure that it worked on Windows, our developers work on Linux and Mac.

May I ask why you're trying to build from source? The libraries are being published to Google's Maven repo, so apps can just use the published ones. If you're trying to run the Tutorial app, note that it has a seperate Gradle project, located in `reference-apps/tutorial`, which use the published libraries and does not involve building any Rust code.

**Comment by HooHaa-code** [comment]
I am trying to run the tutorial app.

I cloned the project an added it to Android studio.  I see these three options in the IDE:

![image](https://github.com/google/automotive-design-compose/assets/64603080/128db8a8-4374-4f66-af9b-0fc63f640e27)

Trying to run the tutorial app from there is giving me the issue.

**Comment by timothyfroehlich** [comment]
I just tried it out on a Windows VM and got a different error, looks like Git doesn't handle symlinks on Windows by default, so the tutorial basically has no gradle.properties set. Should be an easy fix. Would you mind creating a seperate ticket for that? I should be able to fix that soon.

**Comment by timothyfroehlich** [comment]
Merged in main, can be cherrypicked into a patch release if needed.

**Comment by iamralpht** [comment]
Apparently this part is still failing (although the tutorial is building in Windows on every change).

**Comment by HooHaa-code** [comment]
Using commit 92f397b2028129c35e95982abc25290b8441e4f5, i still see the Cargo build issue.  I added a video of how I am attempting to execute the tests as well a screen shot showing the error and the location of cargo on my machine.

![image](https://github.com/google/automotive-design-compose/assets/64603080/98eab86d-05d7-47b3-a9c3-545b62470547)

https://github.com/google/automotive-design-compose/assets/64603080/8467e4e7-de89-4cee-a223-3524fae9818e

**Comment by HooHaa-code** [comment]
@iamralpht @timothyfroehlich It appears I don't have permissions to assign issues.
