### ISSUE TITLE
The tutorial app fails to build on Windows

### ISSUE THREAD

**Issue by HooHaa-code** [google/automotive-design-compose#374]
Trying to run the tutorial app on windows results in this error:

![image](https://github.com/google/automotive-design-compose/assets/64603080/dfe6bb15-e11e-4c20-a66d-cadf1f0840f2)

**Comment by timothyfroehlich** [comment]
@HooHaa-code I'm working out some CI issues, but I believe the changes in #375 should fix things for you. I can't get an emulator hooked up to my Windows VM so I can't test running the Tutorial, but I was able to build everything just fine. (BTW, the lint checks fail but I don't think that causes any issues)
