### ISSUE TITLE
Live Update doesn't automatically start when setting the token

### ISSUE THREAD

**Issue by timothyfroehlich** [google/automotive-design-compose#378]
Reproduction:

1. Take Helloworld, and install on a clean emulator (or uninstall the previous install)
2. Launch app, observe that Live Update is disabled
3. Run the setFigmaTokenDebug task
4. The app will not react either visibly or in Logcat
5. Switch to a different app on the device
6. Switch back to HelloWorld
7. Live update will start and a download will begin fetching.

I've observed this on both HelloWorld and a new, fresh app.
With the new app I tested with both 0.23 and 0.22, the problem appears on both.

**Comment by urpatil** [comment]
This issue still exists.  It looks like the ApiKeyService gets the intent with the right Figma token but the live update part doesn't get triggered.

**Comment by timothyfroehlich** [comment]
Can you confirm that you were using an up-to-date release? If you weren't
using main could you make sure it reproduces on main?
