### ISSUE TITLE
Make the Rust layout manager object an instantiable non-singleton class

### ISSUE THREAD

**Issue by rylin8** [google/automotive-design-compose#475]
This will allow tests to run in parallel, as each test can instantiate its own layout manager. This will require client (Android) and JNI changes. Android will need to instantiate a new layout manager on startup and refer to it for any subsequent layout calls.

**Comment by rylin8** [comment]
I was going to make a map of LayoutManager objects and give each a unique ID. The Android side would call a new JNI function to create one and get an ID back, then it would use that ID in future layout calls. However there's no need for that unless we need multiple layout managers -- can you think of any other reasons we might need this?  Otherwise I can just move the singleton layout manager into jni.rs, make `LayoutManager` functions public, and have the layout tests each instantiate a LayoutManager. Thoughts? @iamralpht @timothyfroehlich

**Comment by iamralpht** [comment]
I think singletons are generally a bad direction, because it's a kind of hidden global state. So no singletons unless it's really needed (like stashing the `JavaVM` pointer in `JNI_OnLoad` into a global).

In this case, I'm not sure when it's best to have one taffy instance, or when to have multiple. So on the Compose side I guess we'd make one and put it in the root-most `CompositionLocal`, then we can move nodes between roots still if needed.

**Comment by timothyfroehlich** [comment]
> However there's no need for that unless we need multiple layout managers -- can you think of any other reasons we might need this? 

Multiple screens?

> I think singletons are generally a bad direction, because it's a kind of hidden global state. So no singletons unless it's really needed (like stashing the JavaVM pointer in JNI_OnLoad into a global).

Agreed here. I think that all singletons need to have a compelling reason to justify being a singleton. 

We need to make sure we're developing with testability in mind and singletons automatically make testing more difficult, especially when they're statically allocated.

**Comment by rylin8** [comment]
I'm not trying to promote singletons. I've removed the one from layout.rs and the unit tests all create their own layout manager instance now and can run with multiple threads. Maybe I'm not understanding JNI correctly, but I'm just trying to find the correct place to store the `LayoutManager` instances in memory when running Android. I don't want to serialized a `LayoutManager` and have Android hold onto it. Maybe `JNIEnv` has some way to store objects within the lifetime of itself?
