### ISSUE TITLE
Rotated frames with background images are cropped

### ISSUE THREAD

**Issue by rylin8** [google/automotive-design-compose#481]
Seems to be an issue with image scaling in `RelativeImageFill`. The scale is calculated off the rotated bounding box instead of the original image size.

Figma:
![Screenshot 2023-10-17 at 11 14 27 PM](https://github.com/google/automotive-design-compose/assets/130500397/fb9606cb-45fb-43ec-86ea-545e3a5645a3)

Android:
![Screenshot 2023-10-17 at 11 14 22 PM](https://github.com/google/automotive-design-compose/assets/130500397/fb7631c4-d4fc-43c6-9b01-1345b3875808)

**Comment by rizniazi** [comment]
This will be fixed in 0.24 release by 10/27.

**Comment by rylin8** [comment]
Hmm I just tried to reproduce this in main and could not. I originally reproduced this in the rustlayout branch and found that the code doing this was in the rendering code, so I assumed it was happening in main as well, but now I'm not sure how this was ever happening in main.

**Comment by rylin8** [comment]
Just to clarify and follow up, this renders correctly in the latest code from main:
![Screenshot 2023-11-02 at 8 39 59 AM](https://github.com/google/automotive-design-compose/assets/130500397/2cf150a5-0fb7-4ec9-b19d-1d755989d952)

**Comment by rylin8** [comment]
@elouannf you mentioned that this was happening awhile ago, but I am unable to reproduce this on our main branch. Do you have any specific reproduction steps?

**Comment by iamralpht** [comment]
Resolving since we're unable to repro.
