### ISSUE TITLE
Support rendering stroked/outlined text

### ISSUE THREAD

**Issue by iamralpht** [google/automotive-design-compose#485]
Stroked or outlined text is used fairly frequently in instrument cluster designs (e.g. for word-based telltales where background contrast is important). Currently DesignCompose supports a single shadow on text, but not stroking or outlining. It looks like Jetpack Compose added support for stroking text in 1.4.0 by adding a `drawStyle` field to the text style object, so hopefully we can just expose that.

**Comment by yiqunw700** [comment]
Added basic support for text stroke: solid, centered text stroke for both non-squoosh and squoosh render.
