### ISSUE TITLE
Release 0.19

### ISSUE THREAD

**Issue by timothyfroehlich** [google/automotive-design-compose#51]
- [x] Cut release on GitHub
- [x] Publish SDK to gMaven
- [x] Publish Updates to Figma Community:
    - [x] Tutorial File
    - [x] Plugin
    - [x] Widget

@rylin8: Do we have any updates to the Plugin and Widget that need to be published?

**Comment by rylin8** [comment]
Yes, the dials & gauges is new in the plugin. The widget may have a small security fix. I'm still working on some bugs and the progress indicator feature for dials & gauges. It would be great to get that in, but if we want to make the build earlier that's fine.

**Comment by timothyfroehlich** [comment]
@iamralpht @rylin8 

Currently both #58 and #54 are marked for the 0.19 release and are outstanding. Are these blockers for a release candidate?

**Comment by rylin8** [comment]
#58 would be great to get in but if I need to make additional changes and it's holding up the release we can delay it.
