### ISSUE TITLE
helloworld app missing wrapper gradle task

### ISSUE THREAD

**Issue by HooHaa-code** [google/automotive-design-compose#511]
using commit 92f397b2028129c35e95982abc25290b8441e4f5, I opened the helloworld app as its own project.  The Gradle sync task fails with the error `Task 'wrapper' not found in project ':helloworld-app'.`

![image](https://github.com/google/automotive-design-compose/assets/64603080/fe15a3e0-ec6c-4d8d-bfab-fea41e621e3c)

**Comment by timothyfroehlich** [comment]
That's true, we hadn't set it up to be a standalone project. Considering
that it's in reference-apps, it probably should be. I'll see about getting
that set up when I get back from vacation.
