### ISSUE TITLE
Ensure Tutorial App can be built with Android Studio Electric Eel

### ISSUE THREAD

**Issue by timothyfroehlich** [google/automotive-design-compose#54]
We want to make sure that the previous stable release is compatible with it.

**Comment by timothyfroehlich** [comment]
@iamralpht I've taken a shot at this and I'd need a day or so to accomplish this.

Problem 1 is that Electric Eel only supports AGP 7.4.2, not 8, which is what everything currently uses. So the assumed easy fix is to pin the Tutorial app's AGP version to 7.4.2. 

But problem 2 is that the Tutorial App is relying on the build-logic subproject for some build config and for the setFigmaToken tasks. The build config is easily solved, but in order to have the setFigmaToken tasks, I would have to separate that code from the build-logic subproject into it's own plugin and publish the plugin to gMaven. I had always intended to do this at some point, after we had more than just the setFigmaToken tasks to publish as a "DesignComposeGradlePlugin", and it would only take a day or less to do this. But until that happens, the Tutorial app will only be compatible with Android Studio Flamingo.

I would like your input here.

**Comment by iamralpht** [comment]
Moving to the current iteration, since we didn't complete this in the previous.

**Comment by iamralpht** [comment]
Update from triage review -- WIP is working, and also creates a new plugin for the setFigmaToken logic. Should be in review later today with some tests on the new work.
