### ISSUE TITLE
Use `serde_json::from_reader` instead of `serde_json::from_str` in document.rs

### ISSUE THREAD

**Issue by iamralpht** [google/automotive-design-compose#582]
Some folks are bumping into `ureq`'s [10MB limit](https://docs.rs/ureq/latest/src/ureq/response.rs.html#466) for `into_string()`, and it's not a configurable limit. Additionally, using `into_string()` on every response means we have at least one copy of the whole doc in heap, and likely more since we use Strings and not slices in the `figma_schema` form.

We should switch to `serde_json::from_reader` and impose our own limit.

**Comment by johnoneil** [comment]
I branched from release 23 and have some code in this area.
Not well tested, but I think it's in the area:

https://github.com/google/automotive-design-compose/tree/wb/johnoneil/serialization-fix

**Comment by timothyfroehlich** [comment]
Thanks, John. I'm going to focus on that this morning.
