### ISSUE TITLE
Need to provide effective mechanisms and instructions for reproducing bugs from external customers.

### ISSUE THREAD

**Issue by timothyfroehlich** [google/automotive-design-compose#648]
In #643 we have a problem in that both us and the user are have tight controls on our Figma organizations, and we aren't finding an obvious way to share a Figma design from them to us.

I believe a solution would be for us to set up a second Figma account/team/plan? which is only for interaction with users, and which would allow us to at least create blank Figma files to share out.

**Comment by iamralpht** [comment]
I think that we can share `.fig` files back and forth for this. If the content is sensitive, then it should be shared via a partner buganizer ticket, rather than via public GitHub issues.

**Comment by timothyfroehlich** [comment]
Forgot to mention that in the original post. They'd tried that but they don't seem to have a menu option to export to `.fig` [(they only had `.png`)](https://github.com/google/automotive-design-compose/issues/643#issuecomment-1861667448).

**Comment by HooHaa-code** [comment]
I was looking in the export menu.  I was able to save a local .fig file.  Github won't let me attach a .fig so I zipped it and was able to save it github

**Comment by timothyfroehlich** [comment]
Ok, sounds good.
