### ISSUE TITLE
Cannot change variant of a component on the stage

### ISSUE THREAD

**Issue by HooHaa-code** [google/automotive-design-compose#691]
I have created a component with one property and three states.  I added six instances of that component to the stage.  I would like to change the property of all six instances individually.  I get an error that my node `Indication=Stop` cannot be found.

An example project and figma file are attached

[Ex4Google-variant.zip](https://github.com/google/automotive-design-compose/files/13822677/Ex4Google-variant.zip)

**Comment by rylin8** [comment]
The way that we normally set variants is by declaring a `@DesignVariant` annotation on a parameter within the main frame. Then, setting that parameter when calling the main frame composable would set that variant for any children instances of the component. These child instances must be named the same as the component itself though, so in your example, `#IndicatorGroup1/Indicator1` would need to be renamed `Indicator`.

To individually set the component instances, the best way to do that currently is to specify replacement components for each one, and then replace them with another copy of the instance with the property set to what you want. For example, the annotations would look something like:

```
    @DesignComponent(node = "#mainFrame", isRoot = true)
    fun mainFrame
        @Design(node = "#IndicatorGroup1/Indicator1") in1: @Composable (ComponentReplacementContext) -> Unit,
    )

    @DesignComponent(node = "Indicator")
    fun indicator1_1(
        @DesignVariant (property = "Indication") indication: Indication
    )
 ```

And then calling the generated code would look like:

```
@Composable
fun Example() {
    ExampleDoc.mainFrame(
        in1 = {
            ExampleDoc.indicator1_1(indication = Indication.Stop)
        }
    )
}
```

**Comment by HooHaa-code** [comment]
Using the provided snippet give me this error
![error](https://github.com/google/automotive-design-compose/assets/64603080/c1cfa01f-9c92-4f0f-98c9-286d16e9d2d1)
here is a snapshot of the figma file
![figma](https://github.com/google/automotive-design-compose/assets/64603080/258f3aea-83b9-4f5a-b404-5eb387421884)

**Comment by rylin8** [comment]
Is live update turned on? Using that code and your attached Figma file, mine is working. Perhaps it would be easier to debug this in our next meeting.
![Screenshot 2024-01-04 at 8 43 57 AM](https://github.com/google/automotive-design-compose/assets/130500397/011d72ca-f479-4985-bd35-ca2ba65589de)

**Comment by HooHaa-code** [comment]
I've asked for a full hour in our next meeting for that exact reason.  We will look at it then.  Thanks for the support

**Comment by rylin8** [comment]
Interesting thing I found is that if `#mainFrame` has a bunch of instances of `Indicator` that are all renamed, the node cannot be found:
![Screenshot 2024-01-10 at 9 16 06 AM](https://github.com/google/automotive-design-compose/assets/130500397/af91942f-0c7b-40c5-9847-f9380173540d)

However if I rename one of those instances to its original name, `Indicator`, then it works.
![Screenshot 2024-01-10 at 9 16 00 AM](https://github.com/google/automotive-design-compose/assets/130500397/5b7dc078-1b78-4353-bcb5-38068928b93f)

**Comment by rylin8** [comment]
Ok I think this might be a limitation in DesignCompose, but I was able to fix this by renaming `Indicator` to `Indication`. So the property used for the indicator component should use "Indication", both in the node name and property name, and the Figma file should match. 

```
@DesignComponent(node = "Indication")
fun indicator1_1(
    @DesignVariant (property = "Indication") indication: Indication
)
```

![Screenshot 2024-01-10 at 3 15 16 PM](https://github.com/google/automotive-design-compose/assets/130500397/ef4b5cd7-79a5-4c05-8ae9-bb9b5829565b)

**Comment by HooHaa-code** [comment]
@rylin8 Here is an updated example file showing the issues i was showing in this morning meeting.  If you remove one of the Indicator components from the stage, the Indicator Group will render the entire variant box:
![image](https://github.com/google/automotive-design-compose/assets/64603080/130eba55-3519-45dd-8914-5b1c9884b530)
[Ex4Google-variant.zip](https://github.com/google/automotive-design-compose/files/14515924/Ex4Google-variant.zip)

**Comment by rylin8** [comment]
Looks like the name of the component "IndicatorLeft" is slightly different than the property name, "IndicationLeft". Once these are made the same it should work. This admittedly is confusing and probably shouldn't need to be named this way, but it's how it works at the moment.
![Screenshot 2024-03-07 at 1 33 50 PM](https://github.com/google/automotive-design-compose/assets/130500397/f4e13c80-4a60-4907-a1c6-6e825c9d1860)
![Screenshot 2024-03-07 at 1 33 50 PM](https://github.com/google/automotive-design-compose/assets/130500397/2430b9f6-40cb-4c21-876a-2d7e322566cb)

**Comment by HooHaa-code** [comment]
🤦 .

I see it working with the recommended naming change
