### ISSUE TITLE
Rust code changes to not get compiled

### ISSUE THREAD

**Issue by rylin8** [google/automotive-design-compose#697]
Changing DesignCompose Rust code and then building/running an application does not trigger a rebuild of the Rust code. Example:

- Open the designcompose root project in Android Studio
- Build and run validation from Android Studio on an emulator
- Add a log line to `layout.rs` in the layout crate, in `add_style()`, such as `info!("add_style!")`
- Build and run validation from Android Studio again
-> It runs immediately without rebuilding, and no log lines are seen.

**Comment by timothyfroehlich** [comment]
I've reproduced it, looking into it.
