### ISSUE TITLE
Bug: Cannot switch design if current one isn't loading

### ISSUE THREAD

**Issue by timothyfroehlich** [google/automotive-design-compose#71]
I'm testing the Tutorial app right now with 0.19.0-rc02 and the serialized file is missing from the checkout. (It should be in `reference-apps/tutorial/app/src/main/assets/figma`, see #72 ). The Design Switcher stays in a loading state and doesn't display the change design button

![image](https://github.com/google/automotive-design-compose/assets/5819722/2fd1a85c-f4f1-4fbe-a732-df4e3fa1c4cf)

Essentially an app in this state is stuck.

**Comment by rylin8** [comment]
I don't think this needs to be fixed for 0.19 if https://github.com/google/automotive-design-compose/issues/72 is fixed.

**Comment by timothyfroehlich** [comment]
> I don't think this needs to be fixed for 0.19 if #72 is fixed.

For an early release like this, that should be fine.

**Comment by iamralpht** [comment]
Agree with @rylin8 and @timothyfroehlich this isn't a blocker for 0.19, but should be fixed soon, as we're starting to see design teams engage.

**Comment by rylin8** [comment]
@timothyfroehlich @iamralpht @miriamvu what if we just add a Change button to the loading view? The scenario in which this bug would occur is probably not common -- it's when the developer use a bad Figma doc in the code. If in fact it is a good doc but the HTTP calls keep failing, we do in fact want to keep retrying, so I don't want to add code to say "abort live update if it fails a bunch". I tested adding a change button in the below view and it works.

![Screenshot 2023-06-27 at 5 06 10 PM](https://github.com/google/automotive-design-compose/assets/130500397/c51d715c-1b5f-4cd8-aac0-9f4d8a7d9b19)

**Comment by timothyfroehlich** [comment]
Yep, seems like a good change in general.
