### ISSUE TITLE
Cannot find a method to test which variant is set to a node

### ISSUE THREAD

**Issue by HooHaa-code** [google/automotive-design-compose#757]
I am looking for a way to test which variant is set to a node.  In the provided example, I have an indicator group with 3 different indicators.  I would like to write 6 tests that test the variants set to each indicator (one test for each indicator).  I am able to find the node of interest, but am not able to discern which variant is currently set.

[Ex4Google-variantTesting.zip](https://github.com/google/automotive-design-compose/files/14089158/Ex4Google-variantTesting.zip)

**Comment by rylin8** [comment]
I have a pull request open currently that adds some component variant tests. It clicks some buttons that set variant parameters, and then checks that the correct variant is shown. However it does this check by looking for text within the variant. You could do this too by adding text to your variants and looking for the text in your tests -- would that work for you? You can see it here https://github.com/google/automotive-design-compose/pull/754/files#diff-eb647c50d5817e172336ebbed35af2fa78cc3fde96ef3644c46e8bfec9d8b68a

**Comment by HooHaa-code** [comment]
I was able to assert tests by setting contentDescription and stateDescription in the semantics modifiers
