### ISSUE TITLE
Progress bars appear to always be a fixed size (800px)

### ISSUE THREAD

**Issue by HooHaa-code** [google/automotive-design-compose#761]
I'd like to have a 100 px wide progress bar.  The plugin seems to force the width to be 800px

https://github.com/google/automotive-design-compose/assets/64603080/eb031b24-85d7-41d1-86fb-dd858945d2c5

**Comment by rylin8** [comment]
The parent frame of the progress bar defines the maximum size of the progress bar, so you'll need to put that rectangle into a parent frame and set the parent frame's width to be 100px. You can click on the little information icon next to "Progress bar fill" to get a little more info.

**Comment by HooHaa-code** [comment]
🤦
