### ISSUE TITLE
Instructions unclear in Tutorial Text 3 pane

### ISSUE THREAD

**Issue by timothyfroehlich** [google/automotive-design-compose#78]
It states "Open the Live Text Format plugin, under DesignCompose"

It needs to state something to the effect of "open plugins, search for Automotive design for Compose, click run, select the Live Text Format option"

**Comment by aubreydagoog** [comment]
Fixed. Updated to: Under **Plugins**, search for **Automotive design for Compose** > **Run** > **Live Text Format**.

**Comment by Methodician** [comment]
Live Text Format option does not exist in the plugin. The tutorial seems to be way out of date (last updated 2 years ago) so I hope there is a newer version available.
