### ISSUE TITLE
Instructions in Tutorial file should better explain how to make a modification

### ISSUE THREAD

**Issue by timothyfroehlich** [google/automotive-design-compose#79]
For instance, the instructions in `Image 1` include "Give it a 60 corner radius" but don't explain how (it's in the **Vector** menu) or give the square a red border (It's in the **Stroke** menu and you need to give it a size greater than 1 to make it visible

**Comment by rylin8** [comment]
@miriamvu Aubrey (is she on Github yet?) could you review?

**Comment by aubreydagoog** [comment]
I guess this depends on how in-depth we want to go in this tutorial. This tutorial was written for basic Figma users. I'm surprised there's an issue with corner radius vs image size or renaming layer names.

**Comment by aubreydagoog** [comment]
If we are going to do a tutorial for brand new people.. then maybe I should make an intro to Figma section.. or we send them to a basic figma tutorial.

**Comment by iamralpht** [comment]
I think we should link to a Figma intro doc/tutorial provided by Figma in the intro, since otherwise we could spend a lot of time going into depth here.

**Comment by timothyfroehlich** [comment]
I think `Image 1`  was the only bit that I felt needed a bit more explanation, most everything else you do is fairly straightforward or already includes instructions on how to do it (like the Widget section explains how to insert a Widget). These ones are just behind menus that might be a little hard to find, and we just need a few words, basically what I put in the ticket description.

**Comment by aubreydagoog** [comment]
I added a link to the intro 2 slide that says, "Learn the basics of using Figma here."
