### ISSUE TITLE
Replacing an absolutely positioned node does not preserve position

### ISSUE THREAD

**Issue by rylin8** [google/automotive-design-compose#792]
A `@Composable (ComponentReplacementContext) -> Unit` type customization on a node that is absolutely positioned (not in an autolayout) will not preserve the position of the original node. To achieve this, we need to somehow provide the position of the node being replaced to the replacement composable and have it use that instead of its own position.

**Comment by rylin8** [comment]
I ran into this issue while experimenting today. I looked into the issue and it did not seem like a quick fix without it being a hack. I'd rather not add another parameter to the already excessively long list of parameters in `DesignView`.

**Comment by HooHaa-code** [comment]
Is this a regression with 0.25?  It seemed to work better in 0.24.  It appears that adding the node to be replaced in it own frame will allow it to position correctly.  However, its making the figma files a bit complicated

**Comment by rylin8** [comment]
@HooHaa-code regarding our discussion on changing the size of a component replacement, you showed an example that roughly looks like this. You were doing a component replacement of #ReplaceMe with a #RedBox. The problem was that if a designer resized #RedBox but not #ReplaceMe, then it would still take the size of #ReplaceMe, which is not desired.
![Screenshot 2024-03-06 at 4 30 08 PM](https://github.com/google/automotive-design-compose/assets/130500397/629452f9-6117-4fa3-8b23-8f53ad021fc7)

Once the pull request for this ticket goes in, you shouldn't need to have a parent frame #ReplaceMe. You can just put #RedBox directly into #stage and rename it to #ReplaceMe. Then, when the component #RedBox changes size, the instance of it in #stage also changes size, so the original and replacement node will always be the same. Does that work for you? Like this:
![Screenshot 2024-03-06 at 4 30 25 PM](https://github.com/google/automotive-design-compose/assets/130500397/78e186ff-296a-4b95-a87e-1d0aa82eb125)
