### ISSUE TITLE
Tutorial - Components 2 - Where is the Current variant window?

### ISSUE THREAD

**Issue by timothyfroehlich** [google/automotive-design-compose#80]
I couldn't figure out how to set the variants names and I can't find a Current variant window. I did figure out how to rename the values by clicking the configuration button for the property. Clicking that button should be included in the instructions.

**Comment by rylin8** [comment]
Not sure what you mean by current variant window. If you click the main component, the parent of the variants, you should be able to configure everything on the right side.

**Comment by timothyfroehlich** [comment]
The screenshot in the Components 2 box shows:

![image](https://github.com/google/automotive-design-compose/assets/5819722/b7a29ed6-90e3-47a1-9519-b2bf48ef740c)

But this is all I see on the right:
![image](https://github.com/google/automotive-design-compose/assets/5819722/fbb89c05-e442-40a7-88dc-edc6ce5a09bc)

I have to click the configuration button to find a place where I can edit the values:
![image](https://github.com/google/automotive-design-compose/assets/5819722/a7756fe2-b21d-48e9-9364-df0527575953)

**Comment by rylin8** [comment]
I'm guessing Figma updated their UI and our screenshot is from the older version.
