### ISSUE TITLE
Tutorial - Clarify Auto Content 4 instructions WRT the "space between" value.

### ISSUE THREAD

**Issue by timothyfroehlich** [google/automotive-design-compose#81]
With the toggle off I can set the space between value.

![image](https://github.com/google/automotive-design-compose/assets/5819722/26fb7270-0bd2-4694-a56a-41c6521ef439)

But with it on I can't change the value. Also the preview in the widget properties doesn't match what's displayed in the widget itself.
![image](https://github.com/google/automotive-design-compose/assets/5819722/52b3da1d-228f-4494-88dd-0a5e29db0b07)

**Comment by rylin8** [comment]
When it's on it spaces them out for you automatically so you can't set the spacing manually, that's intended. I think this is working as intended.

**Comment by timothyfroehlich** [comment]
In that case shouldn't it be labeled something like "Automatic spacing"?  And it  didn't seem like it was automatically spacing them out, you can see them lined up next to each other in the widget preview, so "auto spacing" wouldn't make sense here either.

Try following the instructions in Auto Content 4 to see what I mean. It says "change the space-between to 20", which seems to reference the toggle button.

**Comment by rylin8** [comment]
"Space between" is a flexbox term meaning put the items at the edges and space them out evenly. It doesn't work in this example because the items take up more space than their container. Maybe we can change the wording of "change the space-between" to be more specific, but I wouldn't change the name of the toggle.

**Comment by aubreydagoog** [comment]
Oh, I see. I accidentally double labeled and said "space between" for both cases. I updated the sentence to read: 
Under the Spacing tab, change the **spacing** (_used to be **space between**_) to 20.

**Comment by timothyfroehlich** [comment]
Perfect!
