### ISSUE TITLE
Roborazzi fails when folder doesn't exist

### ISSUE THREAD

**Issue by rylin8** [google/automotive-design-compose#858]
When running `./gradlew recordRoborazziDebug`, I got the failure below. This was fixed after creating the missing directory.

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':media-lib:testDebugUnitTest' (type 'AndroidUnitTest').
  - Type 'com.android.build.gradle.tasks.factory.AndroidUnitTest' property '$1' specifies directory '/usr/local/google/home/rylin/src/automotive-design-compose/reference-apps/aaos-unbundled/media/build/outputs/roborazzi' which doesn't exist.
    
    Reason: An input file was expected to be present but it doesn't exist.
    
    Possible solutions:
      1. Make sure the directory exists before the task is called.
      2. Make sure that the task which produces the directory is declared as an input.
    
    For more information, please refer to https://docs.gradle.org/8.4/userguide/validation_problems.html#input_file_does_not_exist in the Gradle documentation.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

**Comment by timothyfroehlich** [comment]
Unable to reproduce. Please re-open if you can do so.
