### ISSUE TITLE
Cna’t build: failed to run custom build command for `figma_import v0.1.0

### ISSUE THREAD

**Issue by ivh-tel** [google/automotive-design-compose#89]
Hello everyone,

I don’t get the build of the tutorial app running. I get this error: failed to run custom build command for `figma_import v0.1.0

I followed the guide, but did I forget something?

Machine:
MacBook Pro M1
13.3.1

Any help is very welcome. Thanks
Ivo

**Comment by timothyfroehlich** [comment]
Hi, Ivo. I'm assuming that you're trying to build the Tutorial app using the Gradle project in the root of the repository, right? I'm not sure if we have support for building the DesignCompose SDK on M1 at the moment. Could you try instead opening the Tutorial app's stand-alone project in `reference-apps/tutorial`?  That separate project will fetch the pre-built SDK, so your build won't need to compile `figma_import`.

**Comment by timothyfroehlich** [comment]
I believe that error is stating that you don't have the correct version of Java available. Can you try running the build with either JAVA_HOME set to an installation of Java 17 or later or org.gradle.java.home set in your Gradle properties? More info here: https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_environment_variables

I'd tried to set up some automatic handling of the Java version but I don't think I was successful. #54 should help with this and I'm filing #104 as well, which should also help.

**Comment by timothyfroehlich** [comment]
Other solutions for fixing this longer-term would include #93 and/or making it so that the setFigmaToken tasks can read the Figma Token from a file (which means it'd be much easier to run the task from within Android Studio). 

It's all priorities and what enhancements need to come first, we'll discuss it internally soon. 

In the mean time, configuring your Gradle build to use a Java 17 install should fix this problem.

**Comment by ivh-tel** [comment]
Hi @timothyfroehlich, 

thanks a lot. And sorry for my delayed response. Setting org.gradle.java.home to Java 17 worked. I was able to add my Figma API Key via `FIGMA_ACCESS_TOKEN=<MY_ACCESS_TOKEN> \ ./gradlew setFigmaTokenDebug`

When I start the tutorial app it seems to try to fetch the default Figma file. I know I need to change the Figma file ID to my Figma file ID and I thought I do this in the App. But I can’t find a place where I can change it. Does this happen in the app? In the readme file it is described like this: _Click the Change button to switch document IDs, and enter the ID of your copy of the Tutorial Figma File. Click Load and the app will start fetching your file (it'll take about a minute)_ 

But I don’t see a change button. Do you have an idea?

<img width="357" alt="Bildschirmfoto 2023-06-11 um 12 30 06" src="https://github.com/google/automotive-design-compose/assets/113913383/778f353d-92eb-419f-b380-9903f9512b1e">

<img width="330" alt="Bildschirmfoto 2023-06-11 um 12 30 13" src="https://github.com/google/automotive-design-compose/assets/113913383/cc7368b7-8064-4704-8926-8e7c0cad302d">

**Comment by timothyfroehlich** [comment]
I'm glad that worked! Unfortunately now you're hitting #71, with the underlying cause being that the stored Tutorial file in your copy of the source isn't compatible with the version of DesignCompose that your app is trying to build with. If not for #71 that wouldn't really be a problem, and #75 would have also helped here. 

For now, I would recommend an alternative method of setting the file ID, (which I should add to our documentation). Open `reference-apps/tutorial/app/src/main/java/com/android/designcompose/tutorial/MainActivity.kt`. At line 81 (or near it) will be a line that starts with `@DesignDoc`. Replace the ID there with your Figma file ID, then build and launch the app. The app will automatically start fetching your file and you won't need to change it in the design switcher.

**Comment by timothyfroehlich** [comment]
@iamralpht FYI

**Comment by ivh-tel** [comment]
Hi @timothyfroehlich, thanks a lot. That works. The tutorial app is running  🎉

**Comment by timothyfroehlich** [comment]
Glad to hear!
