### ISSUE TITLE
unable to connect to the figma api in a proxy restricted setup.

### ISSUE THREAD

**Issue by mehrmann** [google/automotive-design-compose#90]
As the Android proxy settings are not considered when building the connection to retrieve documents from figma it's unusable in corporate setups that require a proxy.

Could make it work by using this hack using a local proxy on the host system, but obviously this would need to be configurable in some way or retrieved from the android system:

in `crates/figma_import/src/document.rs`:
```rust
#[cfg(not(feature = "http_mock"))]
fn http_fetch(api_key: &str, url: String) -> Result<String, Error> {
    let proxy = ureq::Proxy::new("http://10.0.2.2:3128")?;
    let agent = ureq::AgentBuilder::new()
        .proxy(proxy)
        .build();
    let body = agent.get(url.as_str())
        .set(FIGMA_TOKEN_HEADER, api_key)
        .timeout(Duration::from_secs(90))
        .call()?
        .into_string()?;
    Ok(body)
}
```

**Comment by iamralpht** [comment]
Yeah, we need to support proxies -- we need to expose it from `document.rs`, and the live update library should expose a setter for Android to call. cc @timothyfroehlich @urpatil

**Comment by iamralpht** [comment]
@urpatil I think this ticket was resolved with https://github.com/google/automotive-design-compose/pull/128 -- is that right? (Can we close this ticket now?)

**Comment by iamralpht** [comment]
@urpatil confirms automotive-design-compose work is complete for this task.
