### ISSUE TITLE
Refactor `DesignDocOverride` into more generic `DesignSettings`, and make Squoosh runtime enable-able

### ISSUE THREAD

**Issue by iamralpht** [google/automotive-design-compose#915]
Let's make Squoosh runtime-enable-able instead of a build-time constant. I think we should refactor `DesignDocOverride` to take multiple optional settings, e.g.:

```kotlin
DesignSettings(
  overrideDocId? = null,
  useSquoosh = false,
  openLinkCallback? = null,
  dcCallbacks? = null,
  content: @Composable () -> Unit
)
```

Then you could specify any of these settings without us extending the arguments to the generated Composables. Additionally, we could remove some of the extra args (like `openLinkCallback` and friends) from the generated Composables and clean up the type signatures.

Once we can turn on Squoosh at runtime, let's turn it on for DriverUI at least.

**Comment by timothyfroehlich** [comment]
Questions:

DesignDocOverride affected all Figma documents in the Compose tree. Do we want to fix that here and make DesignSettings be specific to instances of the `*Gen` interfaces?

What do we want to do about openLinkCallback? I don't have a good definition of how it's supposed to work right now, so other than making sure that the one Validation test still works, I don't know how to fix any issues with it.

What do we want to do about backwards compatibility with 0.25? Should I try to make this a seamless change to the main composable?

**Comment by iamralpht** [comment]
Good questions!

1. I think it's OK for squoosh/openLink, etc to propagate all the way. The doc override is the only one that's dubious, and we'd upgrade that by saying "everything from this @DesignDoc/interface should now come from this other docId" as a map, rather than by limiting how far the settings propagates into the tree.
2. Let's ensure that validation passes for openLinkCallback, we can expand test cases too if you see the opportunity once you get into the change.
3. Don't worry about backwards compatibility. We're not API stable yet, so this should be OK ;)

**Comment by timothyfroehlich** [comment]
Next question: Why a CompositionLocal? Each of these settings, except for Squoosh, only apply to the root composable. I think it makes more sense to just provide this object as a parameter for the root composable, which would not pass it to the child composables.

Going along with that, why is DesignDocOverride a CompositionLocal? Why not have the docID just be an argument to the root composable? The docID should only be relevant to the root one, the one that could have the DesignSwitcher and therefore could change the ID, so there's no reason for it to be a CompositionLocal which could be accessed by everything below it.

**Comment by iamralpht** [comment]
`CompositionLocal` is nice because:

- All child Composables get the same values (the `docId` propagation is necessary most of the time -- you want child list items to get the doc override if they came from the same doc as the parent -- you just don't want the docId override to override Composables from another doc instead).
- No need to add settings to every generated composable. We don't really know about "root" vs "non-root" at generation time, and I think it's nice if the generated API is close to the input.

**Comment by timothyfroehlich** [comment]
Ok. I feel like there's a better design there but it's probably not worth the time to try and figure it out.

**Comment by timothyfroehlich** [comment]
I'm going to remove DesignDocOverride from this ticket, since it needs to be changed to work with multiple DesignDocs with different docIds.

**Comment by timothyfroehlich** [comment]
Can I refactor DesignDoc and DesignDoc Internal to a seperate file? I can never find it when I'm looking for it

**Comment by iamralpht** [comment]
Yeah, agree. Let's get this one landed first and gather feedback from our internal & external users (esp as it's an external API change).
