### ISSUE TITLE
Squoosh: animation: individual timeline control

### ISSUE THREAD

**Issue by iamralpht** [google/automotive-design-compose#950]
We'd like to have control over how individual elements that are animated in a transition move, and specify all transitions between different variants of components.

Currently, we have an automatically generated transition in squoosh that goes between all states, and will add some very basic transition control in 0.26, but this isn't sufficient to create most of the sample animations that we want to be able to achieve.

**Comment by rylin8** [comment]
Dupe of https://github.com/google/automotive-design-compose/issues/1567
